name: Publish to PyPI

on:
  workflow_run:
    workflows: ["*"]
    branches: [main]
    types: [completed]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Update apt-get
        run: sudo apt-get update

      - name: Set up Python 3.10.15
        uses: actions/setup-python@v5.3.0
        with:
          python-version: 3.10.15

      - name: Install CMake
        run: sudo apt-get install -y cmake

      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Build
        run: poetry build --no-interaction

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
